
create table groups (
    id bigint primary key generated by default as identity,
    parent_id bigint
        constraint parent
            references groups (id) on update cascade on delete cascade,
    name text not null,
    created_at timestamptz not null default now() 
);

create type group_abilities as enum ('manage', 'invite_others');

create table memberships (
    group_id bigint
        constraint "group"
            references groups (id) on update cascade on delete cascade,
    user_id bigint
        constraint "user"
            references users (id) on update cascade on delete cascade,
    abilities group_abilities[],
    created_at timestamptz not null default now(),
    primary key (group_id, user_id)
);