-- deploy init

create extension if not exists citext;

create table if not exists users (
    id bigint primary key generated by default as identity,
    username citext unique,
    email citext unique,
    created_at timestamptz default now()
);